# Generated by Django 5.0.6 on 2024-05-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_stock_close_stock_high_stock_low_stock_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
